name: olyjs

services:
  build:
    build: .
    container_name: build
    command: npm run build
    volumes:
      - .:/app

  build_dev:
    build: .
    container_name: build_dev
    command: npm run build:dev
    tty: true
    volumes:
      - .:/app
      - /app/node_modules

  serve:
    image: node:20-alpine
    container_name: serve
    working_dir: /app
    command: npx live-server --port=4200 --open=./tests
    volumes:
      - ./dist:/app/dist
      - ./tests:/app/tests
    ports:
      - 4200:4200
