name: olyjs

services:
  build:
    build: .
    container_name: build
    command: npm run build
    volumes:
      - .:/app

  build_dev:
    build: .
    container_name: build_dev
    command: npm run build:dev
    tty: true
    volumes:
      - ./dist:/app/dist
    develop:
      watch:
        - action: sync
          path: /src
          target: /app
          ignore:
            - node_modules/
            - dist/
            - .git/

        - action: restart
          path: tsconfig.json
        - action: restart
          path: tsconfig.dev.json

        - action: rebuild
          path: package.json
        - action: rebuild
          path: package-lock.json

  serve:
    image: node:20-alpine
    container_name: serve
    working_dir: /app
    command: npx live-server --port=4200 --open=tests
    ports:
      - 4200:4200
    develop:
      watch:
        - action: sync
          path: ./tests
          target: /app
