name: olyjs

services:
  web-build:
    build: .
    container_name: web-build
    command: npm run build
    volumes:
      - .:/app

  web-dev:
    build: .
    container_name: web-dev
    command: npm run build:dev
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - /app/node_modules

  serve:
    image: node:20-alpine
    container_name: serve
    working_dir: /app
    command: npx live-server --port=4200 --open=./tests
    volumes:
      - ./build/dist:/app/build/dist
      - ./tests:/app/tests
    ports:
      - 4200:4200
