name: olyjs

services:
  engine-build:
    image: emscripten/emsdk:latest
    container_name: engine-build
    working_dir: /app
    volumes:
      - ./native:/app
      - ./build/native:/app/build/bin
    command: bash -c "mkdir -p build && cd build && emcmake cmake .. && make"

  web-dev:
    build: ./web
    container_name: web-dev
    command: npm run build:dev
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./web:/app
      - ./web/node_modules:/app/node_modules
      - ./build/native:/app/build/native
      - ./build/web:/app/build/dist

  web-build:
    build: ./web
    container_name: web-build
    command: npm run build
    volumes:
      - ./web:/app

  serve:
    image: node:20-alpine
    container_name: serve
    working_dir: /app
    command: npx live-server --port=4200 --open=./tests
    volumes:
      - ./build:/app/build
      - ./tests:/app/tests
    ports:
      - 4200:4200
